package gruposinvestigacion.model.dto;
// Generated 18/11/2016 11:36:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvestigacionAliados generated by hbm2java
 */
@Entity
@Table(name="investigacion_aliados"
    ,catalog="ufps_76"
)
public class InvestigacionAliados  implements java.io.Serializable {


     private int codigocolaborador;
     private InvestigacionEmpresaaliada investigacionEmpresaaliada;
     private Proyecto investigacionProyecto;
     private int cedula;
     private String nombre;
     private String correo;
     private int participacionespecie;
     private int participacionmonetaria;

    public InvestigacionAliados() {
    }

    public InvestigacionAliados(int codigocolaborador, InvestigacionEmpresaaliada investigacionEmpresaaliada, Proyecto investigacionProyecto, int cedula, String nombre, String correo, int participacionespecie, int participacionmonetaria) {
       this.codigocolaborador = codigocolaborador;
       this.investigacionEmpresaaliada = investigacionEmpresaaliada;
       this.investigacionProyecto = investigacionProyecto;
       this.cedula = cedula;
       this.nombre = nombre;
       this.correo = correo;
       this.participacionespecie = participacionespecie;
       this.participacionmonetaria = participacionmonetaria;
    }
   
     @Id 

    
    @Column(name="codigocolaborador", unique=true, nullable=false)
    public int getCodigocolaborador() {
        return this.codigocolaborador;
    }
    
    public void setCodigocolaborador(int codigocolaborador) {
        this.codigocolaborador = codigocolaborador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresaalida_nit", nullable=false)
    public InvestigacionEmpresaaliada getInvestigacionEmpresaaliada() {
        return this.investigacionEmpresaaliada;
    }
    
    public void setInvestigacionEmpresaaliada(InvestigacionEmpresaaliada investigacionEmpresaaliada) {
        this.investigacionEmpresaaliada = investigacionEmpresaaliada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigoproyecto", nullable=false)
    public Proyecto getInvestigacionProyecto() {
        return this.investigacionProyecto;
    }
    
    public void setInvestigacionProyecto(Proyecto investigacionProyecto) {
        this.investigacionProyecto = investigacionProyecto;
    }

    
    @Column(name="cedula", nullable=false)
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="correo", nullable=false, length=30)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="participacionespecie", nullable=false)
    public int getParticipacionespecie() {
        return this.participacionespecie;
    }
    
    public void setParticipacionespecie(int participacionespecie) {
        this.participacionespecie = participacionespecie;
    }

    
    @Column(name="participacionmonetaria", nullable=false)
    public int getParticipacionmonetaria() {
        return this.participacionmonetaria;
    }
    
    public void setParticipacionmonetaria(int participacionmonetaria) {
        this.participacionmonetaria = participacionmonetaria;
    }




}


