package gruposinvestigacion.model.dto;
// Generated 18/11/2016 11:36:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvestigacionEmpresaaliada generated by hbm2java
 */
@Entity
@Table(name="investigacion_empresaaliada"
    ,catalog="ufps_76"
)
public class InvestigacionEmpresaaliada  implements java.io.Serializable {


     private int nit;
     private String nombre;
     private String direccion;
     private int telefono;
     private Set<InvestigacionAliados> investigacionAliadoses = new HashSet<InvestigacionAliados>(0);

    public InvestigacionEmpresaaliada() {
    }

	
    public InvestigacionEmpresaaliada(int nit, String nombre, String direccion, int telefono) {
        this.nit = nit;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public InvestigacionEmpresaaliada(int nit, String nombre, String direccion, int telefono, Set<InvestigacionAliados> investigacionAliadoses) {
       this.nit = nit;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.investigacionAliadoses = investigacionAliadoses;
    }
   
     @Id 

    
    @Column(name="nit", unique=true, nullable=false)
    public int getNit() {
        return this.nit;
    }
    
    public void setNit(int nit) {
        this.nit = nit;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="investigacionEmpresaaliada")
    public Set<InvestigacionAliados> getInvestigacionAliadoses() {
        return this.investigacionAliadoses;
    }
    
    public void setInvestigacionAliadoses(Set<InvestigacionAliados> investigacionAliadoses) {
        this.investigacionAliadoses = investigacionAliadoses;
    }




}


